#Inicializando variables y colocandoles un valor
nombre= "DYLAN ALFONSO PLATA MANJARRES"
edad= 14
Estado= True

#Esta linea me imprime el contenido de una variable
print("Bienvenido", DYLAN ALFONSO PLATA MANJARRES)
print("Tu edad es", 14)

#Uso de la funcion input()
nombre=input("DYLAN ALFONSO PLATA MANJARRES ")
edad=input("14")

#Mostrar el resultado capturado con input()
print("Bienvenido", DYLAN)
print("Tu edad es", 14)
